### ISSUE TITLE
Review Python Code

### ISSUE THREAD

**Issue by gabywald** [gabywald/CurriculumGenerator#39]

**Comment by abhishekpatel946** [comment]
Can pls little bit describe more? How to review code or something else.

**Comment by gabywald** [comment]
Read the code and gives comments / your advice here ?

> Can pls little bit describe more? How to review code or something else.

**Comment by abhishekpatel946** [comment]
> Read the code and gives comments / your advice here?
> 
> > Can pls little bit describe more? How to review code or something else.

okhs sure !

**Comment by gabywald** [comment]
Thanks For your notes : 
1/ - one more thing your script is look like a simple python program. make it more attracive for UX if you've still any pls check this link :- "https://github.com/abhishekpatel946/PassManager-pyScript/tree/master/Screens" here is my script check the images on the link. thakns
2/ - handle the edge case if user not enter any details like- "Number of Jobs elements ?" are not entered then script gives an error. I think you should consider an else statements to avoid those edge cases
3/ - simply display the current time using ctime(), and correct the format of the `strftime()` time.

Some responses and asked details here : 
1/ thx for this : I do not want more UX, but your idea is good as used in your PassManager ! (it makes a more attractive use)
2/ thx for this, good remind : I will treat this 'ASAP'
3/ what is a good time format pattern for you ?

**Comment by abhishekpatel946** [comment]
> Thanks For your notes :
> 1/ - one more thing your script is look like a simple python program. make it more attracive for UX if you've still any pls check this link :- "https://github.com/abhishekpatel946/PassManager-pyScript/tree/master/Screens" here is my script check the images on the link. thakns
> 2/ - handle the edge case if user not enter any details like- "Number of Jobs elements ?" are not entered then script gives an error. I think you should consider an else statements to avoid those edge cases
> 3/ - simply display the current time using ctime(), and correct the format of the `strftime()` time.
> 
> Some responses and asked details here :
> 1/ thx for this : I do not want more UX, but your idea is good as used in your PassManager ! (it makes a more attractive use)
> 2/ thx for this, good remind : I will treat this 'ASAP'
> 3/ what is a good time format pattern for you ?

I think if we're code together and definitely make an awesome python script. I'll be always ready to collab!
